local wk = require("which-key")

wk.add({
  { "<leader>y", ":%y+<cr>", desc = "Yank All Text" },
  { "<leader>q", ":qa!<cr>", desc = "Quit" },
  { "<leader>c", ":Bdelete this<cr>", desc = "Delete Buffer" },
  { "<leader>C", group = "Buffers" },
  { "<leader>Cc", ":Bdelete other<cr>", desc = "All except this" },
  { "<leader>Ca", ":Bdelete all<cr>", desc = "All" },
  { "<leader>f", ":lua require('telescope.builtin').find_files(require('telescope.themes').get_dropdown{previewer = false})<cr>", desc = "Find files" },
  { "<leader>h", ":lua require'hop'.hint_words()<cr>", desc = "Hop" },
  { "<leader>F", ":Telescope live_grep theme=get_dropdown<cr>", desc = "Find Text" },
  { "<leader>p", group = "Plugin" },
  { "<leader>pc", ":Lazy clean<cr>", desc = "Clean" },
  { "<leader>pC", ":Lazy check<cr>", desc = "Check" },
  { "<leader>pd", ":Lazy debug<cr>", desc = "Debug" },
  { "<leader>pi", ":Lazy install<cr>", desc = "Install" },
  { "<leader>ps", ":Lazy sync<cr>", desc = "Sync" },
  { "<leader>pl", ":Lazy log<cr>", desc = "Log" },
  { "<leader>ph", ":Lazy home<cr>", desc = "Home" },
  { "<leader>pH", ":Lazy help<cr>", desc = "Help" },
  { "<leader>pp", ":Lazy profile<cr>", desc = "Profile" },
  { "<leader>pu", ":Lazy update<cr>", desc = "Update" },
  { "<leader>n", group = "Neovim" },
  { "<leader>nr", ":Reload<cr>", desc = "Core Reload" },
  { "<leader>nc", ":e $MYVIMRC<cr>", desc = "Configuration" },
  { "<leader>ns", ":StartupTime<cr>", desc = "StartupTime" },
  { "<leader>ni", ":Inspect<cr>", desc = "Inspect" },
  { "<leader>nu", ":Update<cr>", desc = "Update" },
  { "<leader>nh", ":checkhealth<cr>", desc = "Health" },
  { "<leader>nv", ":version<cr>", desc = "Version" },
  { "<leader>g", group = "Git" },
  { "<leader>gg", ":LazyGit<cr>", desc = "Lazygit" },
  { "<leader>gj", ":lua require 'gitsigns'.next_hunk()<cr>", desc = "Next Hunk" },
  { "<leader>gk", ":lua require 'gitsigns'.prev_hunk()<cr>", desc = "Prev Hunk" },
  { "<leader>gl", ":lua require 'gitsigns'.blame_line()<cr>", desc = "Blame" },
  { "<leader>gp", ":lua require 'gitsigns'.preview_hunk()<cr>", desc = "Preview Hunk" },
  { "<leader>gr", ":lua require 'gitsigns'.reset_hunk()<cr>", desc = "Reset Hunk" },
  { "<leader>gR", ":lua require 'gitsigns'.reset_buffer()<cr>", desc = "Reset Buffer" },
  { "<leader>gs", ":lua require 'gitsigns'.stage_hunk()<cr>", desc = "Stage Hunk" },
  { "<leader>gu", ":lua require 'gitsigns'.undo_stage_hunk()<cr>", desc = "Undo Stage Hunk" },
  { "<leader>go", ":Telescope git_status<cr>", desc = "Open changed file" },
  { "<leader>gb", ":Telescope git_branches<cr>", desc = "Checkout branch" },
  { "<leader>gc", ":Telescope git_commits<cr>", desc = "Checkout commit" },
  { "<leader>gd", ":Gitsigns diffthis HEAD<cr>", desc = "Diff" },
  { "<leader>l", group = "LSP" },
  { "<leader>lf", ":lua vim.lsp.buf.format()<cr>", desc = "Format" },
  { "<leader>la", ":Lspsaga code_action<cr>", desc = "Code Action" },
  { "<leader>lh", ":lua vim.lsp.buf.signature_help()<cr>", desc = "Signature Help" },
  { "<leader>li", ":LspInfo<cr>", desc = "Info" },
  { "<leader>lo", ":Lspsaga outline<cr>", desc = "Code Outline" },
  { "<leader>lI", ":Lspsaga incoming_calls<cr>", desc = "Incoming Calls" },
  { "<leader>lO", ":Lspsaga outgoing_calls<cr>", desc = "Outgoing Calls" },
  { "<leader>lm", ":Mason<cr>", desc = "Mason Installer" },
  { "<leader>lj", ":Lspsaga diagnostic_jump_next<cr>", desc = "Next Diagnostic" },
  { "<leader>lk", ":Lspsaga diagnostic_jump_prev<cr>", desc = "Prev Diagnostic" },
  { "<leader>ld", ":Telescope diagnostics bufnr=0<cr>", desc = "Document Diagnostics" },
  { "<leader>lw", ":Telescope diagnostics<cr>", desc = "Workspace Diagnostics" },
  { "<leader>ls", ":Telescope lsp_document_symbols<cr>", desc = "Document Symbols" },
  { "<leader>lS", ":Telescope lsp_workspace_symbols<cr>", desc = "Workspace Symbols" },
  { "<leader>lc", ":lua require('copilot.suggestion').toggle_auto_trigger()<cr>", desc = "Copilot Toggle" },
  { "<leader>lC", group = "ChatGPT" },
  { "<leader>lCc", "<cmd>ChatGPT<CR>", desc = "ChatGPT" },
  { "<leader>lCe", "<cmd>ChatGPTEditWithInstruction<CR>", desc = "Edit with instruction", mode = { "n", "v" } },
  { "<leader>lCg", "<cmd>ChatGPTRun grammar_correction<CR>", desc = "Grammar Correction", mode = { "n", "v" } },
  { "<leader>lCt", "<cmd>ChatGPTRun translate<CR>", desc = "Translate", mode = { "n", "v" } },
  { "<leader>lCk", "<cmd>ChatGPTRun keywords<CR>", desc = "Keywords", mode = { "n", "v" } },
  { "<leader>lCd", "<cmd>ChatGPTRun docstring<CR>", desc = "Docstring", mode = { "n", "v" } },
  { "<leader>lCa", "<cmd>ChatGPTRun add_tests<CR>", desc = "Add Tests", mode = { "n", "v" } },
  { "<leader>lCo", "<cmd>ChatGPTRun optimize_code<CR>", desc = "Optimize Code", mode = { "n", "v" } },
  { "<leader>lCs", "<cmd>ChatGPTRun summarize<CR>", desc = "Summarize", mode = { "n", "v" } },
  { "<leader>lCf", "<cmd>ChatGPTRun fix_bugs<CR>", desc = "Fix Bugs", mode = { "n", "v" } },
  { "<leader>lCx", "<cmd>ChatGPTRun explain_code<CR>", desc = "Explain Code", mode = { "n", "v" } },
  { "<leader>lCr", "<cmd>ChatGPTRun roxygen_edit<CR>", desc = "Roxygen Edit", mode = { "n", "v" } },
  { "<leader>lCl", "<cmd>ChatGPTRun code_readability_analysis<CR>", desc = "Code Readability Analysis", mode = { "n", "v" } },
  { "<leader>d", group = "Dap" },
  { "<leader>dc", ":lua require'dap'.continue()<cr>", desc = "Continue" },
  { "<leader>do", ":lua require'dap'.step_over()<cr>", desc = "Step Over" },
  { "<leader>di", ":lua require'dap'.step_into()<cr>", desc = "Step Into" },
  { "<leader>du", ":lua require'dap'.step_out()<cr>", desc = "Step Out" },
  { "<leader>db", ":lua require'dap'.toggle_breakpoint()<cr>", desc = "Breakpoint" },
  { "<leader>dd", ":lua require'dapui'.toggle()<cr>", desc = "Dap UI" },
  { "<leader>dL", group = "Lua" },
  { "<leader>dLr", ":lua require'osv'.run_this()<cr>", desc = "Run This" },
  { "<leader>dLl", ":lua require'osv'.launch({port = 8086})<cr>", desc = "Lua Launcher" },
  { "<leader>s", group = "Search" },
  { "<leader>sa", ":Telescope autocommands<cr>", desc = "Autocommmands" },
  { "<leader>sb", ":Telescope git_branches<cr>", desc = "Checkout branch" },
  { "<leader>sc", ":Telescope colorscheme<cr>", desc = "Colorscheme" },
  { "<leader>sh", ":Telescope help_tags<cr>", desc = "Find Help" },
  { "<leader>sk", ":Telescope keymaps<cr>", desc = "Keymaps" },
  { "<leader>sC", ":Telescope commands<cr>", desc = "Commands" },
  { "<leader>sr", ":Telescope oldfiles<cr>", desc = "Recent File" },
  { "<leader>sH", ":Telescope highlights<cr>", desc = "Highlights" },
  { "<leader>t", group = "Terminal" },
  { "<leader>tf", ":ToggleTerm direction=float<cr>", desc = "Float" },
  { "<leader>th", ":ToggleTerm size=10 direction=horizontal<cr>", desc = "Horizontal" },
  { "<leader>tv", ":ToggleTerm size=50 direction=vertical<cr>", desc = "Vertical" },
  { "<leader>O", group = "Octo" },
  { "<leader>Op", "<cmd>Octo pr list<cr>", desc = "PR List" },
  { "<leader>OP", group = "Pull Request" },
  { "<leader>OPd", "<cmd>Octo pr diff<cr>", desc = "Diff" },
  { "<leader>OPc", "<cmd>Octo pr commits<cr>", desc = "Commits" },
  { "<leader>OPC", "<cmd>Octo pr changes<cr>", desc = "Changes" },
  { "<leader>OPe", "<cmd>Octo pr check<cr>", desc = "Check" },
  { "<leader>OPr", "<cmd>Octo pr reload<cr>", desc = "Reload" },
  { "<leader>Or", group = "Review" },
  { "<leader>Ors", "<cmd>Octo review start<cr>", desc = "Start Review" },
  { "<leader>Orc", "<cmd>Octo review create<cr>", desc = "Create Review" },
  { "<leader>Orr", "<cmd>Octo review resume<cr>", desc = "Resume Review" },
  { "<leader>OrS", "<cmd>Octo review submit<cr>", desc = "Submit Review" },
  { "<leader>OR", group = "Reaction" },
  { "<leader>ORy", "<cmd>Octo reaction thumbs_up<cr>", desc = "👍" },
  { "<leader>ORp", "<cmd>Octo reaction +1<cr>", desc = "+1" },
  { "<leader>ORr", "<cmd>Octo reaction rocket<cr>", desc = "🚀" },
  { "<leader>ORP", "<cmd>Octo reaction party<cr>", desc = "🥳" },
  { "<leader>Oc", group = "Comments" },
  { "<leader>Occ", "<cmd>Octo comment add", desc = "Add Comment" },
  { "<leader>Ocd", "<cmd>Octo comment delete", desc = "Delete Comment" },
  { "<leader>Oi", group = "Issues" },
  { "<leader>Oil", "<cmd>Octo issue list<cr>", desc = "List Issues" },
  { "<leader>Oic", "<cmd>Octo issue create<cr>", desc = "Create Issue" },
  { "<leader>j", group = "Jester" },
  { "<leader>jr", ":lua require'jester'.run()<cr>", desc = "Run" },
  { "<leader>jR", ":lua require'jester'.run({repeatable = true})<cr>", desc = "Run Repeatable" },
  { "<leader>jf", ":lua require'jester'.run_file()<cr>", desc = "Run File" },
  { "<leader>js", ":lua require'jester'.stop()<cr>", desc = "Stop" },
  { "<leader>jl", group = "Log" },
  { "<leader>jll", ":lua require'jester'.log()<cr>", desc = "Log" },
  { "<leader>jlL", ":lua require'jester'.log({clear = true})<cr>", desc = "Log Clear" },
  { "<leader>jd", group = "Debug" },
  { "<leader>jdd", ":lua require'jester'.debug()<cr>", desc = "Debug" },
  { "<leader>jdD", ":lua require'jester'.debug({clear = true})<cr>", desc = "Debug Clear" },
  { "<leader>jdf", ":lua require'jester'.debug_file()<cr>", desc = "Debug File" },
  { "<leader>jt", group = "Trace" },
  { "<leader>jtt", ":lua require'jester'.trace()<cr>", desc = "Trace" },
  { "<leader>jtT", ":lua require'jester'.trace({clear = true})<cr>", desc = "Trace Clear" },
  { "<leader>S", group = "Saga" },
  { "<leader>So", ":Lspsaga outline<cr>", desc = "Outline" },
  { "<leader>Sa", ":Lspsaga code_action<cr>", desc = "Code Action" },
  { "<leader>SA", group = "PHP Code Action" },
  { "<leader>SAa", ":GetAllClasses<cr>", desc = "All Classes" },
  { "<leader>SAc", ":GetClass<cr>", desc = "Get Classes" },
  { "<leader>SAs", ":SortClass<cr>", desc = "Sort Classes" },
  { "<leader>Sf", ":Lspsaga lsp_finder<cr>", desc = "LSP Finder" },
  { "<leader>Sh", ":Lspsaga hover_doc<cr>", desc = "Hover Doc" },
  { "<leader>Sp", ":Lspsaga preview_definition<cr>", desc = "Preview Definition" },
  { "<leader>Sr", ":Lspsaga rename<cr>", desc = "Rename" },
  { "<leader>Ss", ":Lspsaga signature_help<cr>", desc = "Signature Help" },
  { "<leader>St", ":Lspsaga open_floaterm<cr>", desc = "Open Floaterm" },
  { "<leader>ST", ":Lspsaga close_floaterm<cr>", desc = "Close Floaterm" },
  { "<leader>Sl", ":Lspsaga show_line_diagnostics<cr>", desc = "Show Line Diagnostics" },
  { "<leader>SL", ":Lspsaga show_cursor_diagnostics<cr>", desc = "Show Cursor Diagnostics" },
  { "<leader>Sb", ":Lspsaga show_buf_diagnostics<cr>", desc = "Show Buffer Diagnostics" },
  { "<leader>Sc", group = "Call Hierarchy" },
  { "<leader>Sci", ":Lspsaga lsp_finder<cr>", desc = "Incoming Calls" },
  { "<leader>Sco", ":Lspsaga lsp_finder<cr>", desc = "Outgoing Calls" },
  { "<leader>w", ":Weather<cr>", desc = "Weather" },
  { "<leader>i", ":Telescope import<cr>", desc = "Telescope Import" },
  { "<leader>N", group = "NeoTest" },
  { "<leader>Nr", ":lua require('neotest').run.run()<cr>", desc = "Run" },
  { "<leader>Nf", ":lua require('neotest').run.run(vim.fn.expand('%'))<cr>", desc = "Run File" },
  { "<leader>Ns", ":lua require('neotest').run.stop()<cr>", desc = "Stop" },
  { "<leader>r", group = "Actions" },
  { "<leader>rr", ":lua require('ssr').open()<CR>", desc = "Rename" },
  { "<leader>rR", ":lua require('refactoring').select_refactor()<CR>", desc = "Refactor" },
  { "<leader>u", group = "Url View" },
  { "<leader>uu", ":UrlView<cr>", desc = "View Buffer URLs" },
  { "<leader>uf", ":UrlView file<cr>", desc = "Open file URLs" },
  { "<leader>ul", ":UrlView lazy<cr>", desc = "Open lazy URLs" },
  { "<leader>z", ":ZenMode<cr>", desc = "Zen Mode" },
  { "<leader>E", ":NvimTreeFindFileToggle<cr>", desc = "Explorer" }
})

return wk

